### ISSUE TITLE
that shit needs to be updated for Monterey

### ISSUE THREAD

**Issue by godbout** [godbout/alfred-airpodspro-connector#1]
![Screen Shot 2021-11-25 at 00 45 51](https://user-images.githubusercontent.com/121373/143280119-87d1c38b-f44d-4d2f-9296-61f4af95233f.png)

**Comment by addisonjames** [comment]
Yes also having the same issue with Monterey and the new MBP.

**Comment by godbout** [comment]
yeah, Monterey is shit. some MAC addresses are returned with hyphens, some with colons. a fucking nightmare. the workflow for the batteries is completely fucked up too. not sure it's worth working that again. seems i'd need to do it from scratch.

**Comment by godbout** [comment]
for the time being try updating manually your MAC address in the workflow config by replacing hyphens with colons, like below:

![Sound_and_Item-0_and_Clock](https://user-images.githubusercontent.com/121373/143487174-1c261e79-ac80-4c1d-9dbf-b108fb13cc87.jpg)

not sure the workflow still works properly actually, or even if it's possible, now that Monterey do the automatic switching blah blah blah.

**Comment by godbout** [comment]
done. download v2.
