### ISSUE TITLE
Handle quotes in headphone name

### ISSUE THREAD

**Issue by jkp** [godbout/alfred-airpodspro-connector#10]
Hi

I needed to make a small tweak to enable the script to correctly handle single quotes (which is often the default in the name given to a pair of airpods by the system as in "Jamie's Airpods").

`NAME=$(grep -B9 "Minor Type: Headphones" <<< "${SYSTEM_PROFILER}" | awk '/AirPods/{ print }' | sed -e 's/^ *//' -e 's/://' | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read())[1:-1])')
`

HTH!

**Comment by godbout** [comment]
strange. i definitely have a `'` in my `G.'s AirPods Pro` and never had an issue. will check. thanks.

**Comment by godbout** [comment]
@jkp probably best is you do a PR for that? 😅️

**Comment by godbout** [comment]
https://github.com/godbout/alfred-airpodspro-connector/releases/tag/4.0.0
