### ISSUE TITLE
'connect' dialog doesn't show AirPods' name

### ISSUE THREAD

**Issue by holamau** [godbout/alfred-airpodspro-connector#11]
Hello, 

do you know why the AirPods name wouldn't show in the 'connect' dialog? 

Funny thing is that it works just fine on a second Mac I have.

<img width="694" alt="ScreenShot 2023-07-20 at 11 34 02 AM" src="https://github.com/godbout/alfred-airpodspro-connector/assets/6577028/904b24e5-58aa-4ba5-b5bf-6af910e5162e">

**Comment by holamau** [comment]
oh, looks like if the AirPods' name starts with 'AirPods' it doesn't show the name... Maybe would be good to add an extra Note or Caveat about it.
<img width="806" alt="ScreenShot 2023-07-20 at 11 50 02 AM" src="https://github.com/godbout/alfred-airpodspro-connector/assets/6577028/26cdd806-8852-405d-9360-335e239e47ec">

**Comment by godbout** [comment]
@holamau does this Workflow actually still works? i haven't been able to use it properly on Ventura, and i think Monterey too. no?

regarding the name issue, possible. i'm lazy and build first for myself, update when people want more stuff or discover bugs. i can work on that rather than adding a caveat. so i reopen.

**Comment by godbout** [comment]
works here when name starts with `AirPods`. gonna make a release tho that fixes a couple of issues.

**Comment by holamau** [comment]
@godbout yes, it works... I would say partially but does the job for me:

the Bluetooth Connector is definitely not working for anything other than 'Connect'. Disconnecting doesn't work at all, but I am happy that it _Connects_, that's all I care about, I have two side-by-side Macs and I switch between them back and forth.  As long as I can just Connect to either with Alfred, I am perfectly happy with it.

And yeah, I am not sure what's up with the name. I'm just going to leave it alone as it works for me. 

Thanks for responding.

**Comment by godbout** [comment]
@holamau sorry, i'm getting confused. have you tried the new v4? should connect and disconnect. it's using an integrated bluetooth utility now. much better.

**Comment by godbout** [comment]
in case you really want to debug the name thing i can send you a couple of commands to run through the Terminal :D

**Comment by godbout** [comment]
actually that could be fun to check. can you run this `system_profiler SPBluetoothDataType 2>/dev/null` on the failing Mac and paste the result? thanks.

**Comment by holamau** [comment]
😆 I just read your release notes. I will do that this week at some point. Is this the BlueUtil you are referring to now?
https://github.com/toy/blueutil

Thanks for the follow up.

**Comment by holamau** [comment]
You can close this now as I will probably update and if I run into issues, I will let you know.

**Comment by godbout** [comment]
> 😆 I just read your release notes.

oh so you're the one who does this.

> Is this the BlueUtil you are referring to now? https://github.com/toy/blueutil

correct. this one works properly. it's included in the Workflow, both for arm64 and i386 CPUs.

**Comment by godbout** [comment]
> You can close this now as I will probably update and if I run into issues, I will let you know.

ok. but i'm very curious about the name missing. i misunderstood your first post actually, i thought the whole thing wasn't working. sure you don't want to figure this out? if no then you can close the issue, yeah. else we can debug.

**Comment by holamau** [comment]
Sorry it took me almost two months to upgrade to v4. Now I have `blueutil` running and v4. It works like a charm. Before I couldn't disconnect the AirPods, which wasn't a real issue. but now I can do either. 

Thank you so much!

**Comment by godbout** [comment]
no worries. nice. btw `blueutil` is packed in the Workflow. both versions, for arm and Intel.
