### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by charys117** [godbout/alfred-airpodspro-connector#2]
Problem of syntax?
<img width="836" alt="截屏2021-12-08 18 23 13" src="https://user-images.githubusercontent.com/42903955/145192091-d370f911-5198-4e09-9ffe-508a6fc4d610.png">
fix MAC to airpods can fix this

**Comment by davosian** [comment]
Disconnected headphones use fewer lines of output (e.g. no battery levels shown), therefore the `grep` offsets are wrong which could catch more than one IP. To fix this, we could grab the last IP address only:

`MAC_ADDRESS=$(grep -B8 "Minor Type: Headphones" <<< "${SYSTEM_PROFILER}" | awk '/Address/{ lastline = $2 } END { print lastline }')`

At least this fixed it for me (2nd gen Airpods - not Pro, M1 Mac on Monterey)

**Comment by paulrudy** [comment]
@davosian works for me too! AirPods Pro, M1 Mac on Monterey. Submit a PR?

**Comment by davosian** [comment]
> @davosian works for me too! AirPods Pro, M1 Mac on Monterey. Submit a PR?

Done already. See PR https://github.com/godbout/alfred-airpodspro-connector/pull/3

**Comment by paulrudy** [comment]
Oops. should have checked, thanks!

**Comment by godbout** [comment]
hey sorry guys. i think GH may have changed some settings in how repositories are watched and i haven't received any notification. i'm seeing since on a lot of my repos. usually i respond very quickly. anyways, will review/merge/update. thanks and sorry again.

**Comment by godbout** [comment]
ok, merged. sorry for the late. will review all the GH notification shit. i'm dismayed.
