### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by golaniy** [godbout/alfred-airpodspro-connector#5]
when searching for 'app' the scripts just crashes and Alfred defaults for the default searches

**Comment by thecael** [comment]
The open pull request seems to fix the issue. It's a problem with the parsing of multiple MAC addresses. 

https://github.com/godbout/alfred-airpodspro-connector/pull/3/commits

**Comment by godbout** [comment]
sorry guys, don't know what's happening with GitHub but i stop receiving notifications.

**Comment by godbout** [comment]
i've made an update for macOS 12.3. will check the PR soon.

**Comment by godbout** [comment]
PR merged. please update to 3.0.1 and let me know thanks.

**Comment by godbout** [comment]
https://github.com/godbout/alfred-airpodspro-connector/releases/tag/4.0.0
