### ISSUE TITLE
readme doesn't mention installation of bluetoothconnector

### ISSUE THREAD

**Issue by dejuknow** [godbout/alfred-airpodspro-connector#6]
Wasn't obvious to me that I need to install the bluetoothconnector package through brew. Should be mentioned somewhere in the readme.

**Comment by godbout** [comment]
sorry, not getting notifications. only seeing now.
yes you're right. i'm pretty sure it was there before, and pointing to the fork's README. i'll add thanks.

**Comment by godbout** [comment]
done: https://github.com/godbout/alfred-airpodspro-connector#setup

thanks. definitely right, should have been mentioned when i made the README update.
