### ISSUE TITLE
Add support for Airpods MAX

### ISSUE THREAD

**Issue by RedcoatAsher** [godbout/alfred-airpodspro-connector#9]
Please add support for Apple Airpods Max.

**Comment by godbout** [comment]
the Workflow actually grabs any type of AirPods: https://github.com/godbout/alfred-airpodspro-connector/blob/0a26642a71e650738634c72f2eac9c219c4af150/src/connector.sh#L5

normal, pro, max. without debug info i can't help more.

also please make sure that 1) you've installed bluetooth connector 2) you're not using multiple AirPods.

**Comment by godbout** [comment]
https://github.com/godbout/alfred-airpodspro-connector/releases/tag/4.0.0
